apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: plex
  name: plex-server
  namespace: plex
spec:
  host: ocp-plex.redcloud.land #fqdn
  port:
    targetPort: plex
  to:
    kind: Service
    name: plex-svc
    weight: 100
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  labels:
    app: plex
  name: secure-plex
  namespace: plex
spec:
  host: secure-plex.apps.openshift.redcloud.land
  port:
    targetPort: https
  tls:
    termination: passthrough
  to:
    kind: Service
    name: plex-svc
    weight: 100
  wildcardPolicy: None