apiVersion: v1
kind: Service
metadata:
  name: plex-port
  namespace: plex
  labels:
    app: plex
spec:
  type: NodePort
  ports:
    - name: plex
      port: 32400
      protocol: TCP
      targetPort: 32400
      nodePort: 32400
  selector:
    app: plex
---
apiVersion: v1
kind: Service
metadata:
  name: plex-web
  namespace: plex
  labels:
    app: plex
spec:
  ports:
    - name: http
      port: 80
      targetPort: plex
    - name: https
      port: 443
      protocol: TCP
      targetPort: 32443
  selector:
    app: plex
